### PR TITLE
Add support for magnet link creation

### PR DESCRIPTION
**Pull request by vitorhcl**
Implements --link/-L using the following syntax:
python3.? pico-torrent -L file
--file/-f and --link/-L cannot be used together

### CODE REVIEW

**Comment by vitorhcl** [comment]
Even though -L and -f are mutually exclusive, it is possible to use, for example, --seeding and --link at the same time, which does makes no sense. These options are ignored, so we could either leave it this way or turn -L into a boolean option to be used with -f.
Another option I was looking for is transforming --link and --file into sub-commands (which have no short options), but that it's a bit more complicated and perhaps not a good option.

**Comment by takusuman** [comment]
> Even though -L and -f are mutually exclusive, it is possible to use, for example, --seeding and --link at the same time, which does makes no sense. These options are ignored, so we could either leave it this way or turn -L into a boolean option to be used with -f. Another option I was looking for is transforming --link and --file into sub-commands (which have no short options), but that it's a bit more complicated and perhaps not a good option.

I will remember this, thanks!

**Comment by takusuman** [comment]
> These options are ignored, so we could either leave it this way or turn -L into a boolean option to be used with -f.

I've read this now and this option sounds simpler than creating other two commands, unless we're going to create a set of tools instead of just a standalone script.

Sorry for not reading all your pull-request before, I've been busy lately.

**Comment by vitorhcl** [comment]
No problem. From what I've seen the syntax would be like:
pico-torrent download -f FILE [-s] [-d]...
pico-torrent link -f LINK
This is kinda weird, and as you said, this is good enough for this script, at least for now.

**Pull request merged**
